from datetime import datetime

from pydantic import BaseModel


class CasePoint(BaseModel):
    claim: str
    evidence: str


class CaseOut(BaseModel):
    side: str
    case_strength: str
    summary: str
    points: list[CasePoint]
    strongest_counterpoint: str
    filings_assessment: str = ""


class LevelOut(BaseModel):
    label: str
    price: float
    basis: str


class AnalysisResponse(BaseModel):
    ticker: str
    created_at: datetime
    model: str
    price_at_analysis: float

    action: str
    confidence: str
    horizon_days: int
    entry: LevelOut
    target: LevelOut
    stop: LevelOut
    risk_reward: float | None

    reasoning: str
    invalidation: str
    disagreement: str

    bull: CaseOut
    bear: CaseOut
    articles_considered: int

    disclaimer: str = (
        "Generated by AI for research only. Not financial advice, and not a prediction "
        "of what the market will do."
    )
